name: "Coffe Setup"

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:     
      - uses: GitLabBR/cupypi@v4.3
        with:
          username: caique9014
          password: familia_carvalho
        env:
          TWINE_PASSWORD: familia_carvalho
          TWINE_USERNAME: caique9014
        
        
