name: "Coffe Setup"

on: 
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:     
      - uses: GitLabBR/cupypi@v4.4
        with:
          username: caique9014
          password: ${{ secrets.PYPI_API_PASSWORD }}
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_PASSWORD }}
          TWINE_USERNAME: caique9014
        
        
